name: Feature Request
description: You want a new feature for gX
title: 'feat: '
labels: ["enhancement", "feature"]

body:
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature you want
      description: A clear and concise description of the feature you want.
    validations:
      required: true

  - type: textarea
    id: related-problem
    attributes:
      label: Describe the problem your feature is related to
      description: A clear and concise description of waht the problem is. Ex. I'm always frustrated when [...]
