name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
    paths:
      - "docker/**"
      - "graphenex/**"
  push:
    branches: [ master ]
    paths:
      - "docker/**"
      - "graphenex/**"

jobs:
  setup_linux:
    name: Linux setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install poetry
        uses: snok/install-poetry@v1

      - name: Install grapheneX
        run: |
          poetry install

      - name: Python import issue workaround
        run: |
          sed -i '/Mapping/s/collections/collections.abc/' \
            /home/runner/.cache/pypoetry/virtualenvs/graphenex--sEiZHBC-py3.10/lib/python3.10/site-packages/prompt_toolkit/styles/from_dict.py

      - name: Run grapheneX
        run: poetry run grapheneX

  setup_windows:
    name: Windows setup
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install poetry
        uses: snok/install-poetry@v1

      - name: Install grapheneX
        run: |
          poetry install

      - name: Python import issue workaround
        shell: pwsh
        run: (Get-Content C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\graphenex-6fD1lE0z-py3.10\lib\site-packages\prompt_toolkit\styles\from_dict.py) -Replace 'from collections import Mapping', 'from collections.abc import Mapping' | Set-Content C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\graphenex-6fD1lE0z-py3.10\lib\site-packages\prompt_toolkit\styles\from_dict.py

      - name: Update Flask-SocketIO
        run: python -m pip install --upgrade flask_socketio

      - name: Run grapheneX
        run: poetry run grapheneX