name: Ruff

on:
  push:
    branches: [ master ]
    paths:
      - 'grapheneX/**/*.py'
  pull_request:
    branches: [ master ]
    paths:
      - 'grapheneX/**/.py'

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ruff
        uses: chartboost/ruff-action@v1
        with:
          args: check .